---
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: argo-cd-01
  annotations:
    module.app.terraform.io/time: "this"
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: hcp-terraform-operator
      key: token
  destroyOnDeletion: true
  restartedAt: "1"
  module:
    source: github.com/arybolovlev/terraform-provider-module-random?ref=0.0.19
  variables:
  - name: username_length
  - name: secret_length
  outputs:
    - name: secret
      sensitive: true
    - name: username
      sensitive: false
  workspace:
    name: argo-cd-01
