---
apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: this
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  destroyOnDeletion: true
  module:
    source: github.com/arybolovlev/terraform-provider-module-random?ref=0.0.19
  variables:
  - name: username_length
  - name: secret_length
  outputs:
    - name: secret
      sensitive: true
    - name: username
      sensitive: false
  workspace:
    name: kubernetes-operator-this
