---
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: argo-cd-01
spec:
  organization: kubernetes-operator
  token:
    secretKeyRef:
      name: hcp-terraform-operator
      key: token
  name: argo-cd-01
  description: Kubernetes Operator Automated Workspace
  applyMethod: auto
  allowDestroyPlan: true
  executionMode: agent
  agentPool:
    name: argo
  terraformVariables:
    - name: username_length
      value: "8"
      hcl: false
      sensitive: false
    - name: secret_length
      value: "8"
      hcl: false
      sensitive: false
